### PR TITLE
New images

### PR DESCRIPTION
**Pull request by mayeut**
I added a few images that were useful for my coverage tests.
HTML doc updated as well as checksums
Old checksums have not changed.
New bitfield images follow the comment in #1 (that is 52 or 56 header size)

### CODE REVIEW

**Comment by mayeut** [comment]
To follow up what was discussed in #1, bitfields images with 52 or 56 header size are in the questionable directory. They seem to be decoded fine (most of them, thus not related to header size).

**Comment by jsummers** [comment]
I'm reviewing your new images. I like what you've done, but I want to at least make some changes to it, and it may take some time.

**Comment by mayeut** [comment]
@jsummers, if you need me to make changes to ease your review please let me know.

**Comment by jsummers** [comment]
I'll merge this soon, but I'm modifying the files that have 52- and 56-byte headers (and adding new files with those header sizes), and maybe making other changes.

**Pull request merged**
